services:
  - type: web
    name: australian-mouthpiece-exchange-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://mouthpieceexchange.org
      - key: DATABASE_URL
        fromDatabase:
          name: australian-mouthpiece-exchange-db
          property: connectionString

databases:
  - name: australian-mouthpiece-exchange-db
    databaseName: mouthpiece_exchange
    user: mouthpiece_user
    plan: free 